"""
Code Runner for Lab 5 — Execute pytest and capture results.

Allows students to run tests from within the notebook.
"""

import subprocess
import tempfile
import os
import sys


def run_tests(code_str, test_file_path, module_name="taskflow.intervals",
              function_name="merge_intervals"):
    """
    Write generated code to a module file and run pytest against test file.

    Args:
        code_str: The generated function code as a string.
        test_file_path: Path to the pytest test file.
        module_name: Dotted module path (e.g., "taskflow.intervals").
        function_name: Function name to inject.

    Returns:
        dict with: returncode, stdout, stderr, passed, failed, errors
    """
    # Determine file path from module name
    parts = module_name.split(".")
    file_path = os.path.join(*parts) + ".py"

    # Read existing file to preserve docstring/imports
    backup = None
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            backup = f.read()

    # Write the new code
    module_code = f'"""\nAuto-generated by Lab 5 code runner.\n"""\n\n{code_str}\n'
    try:
        with open(file_path, "w") as f:
            f.write(module_code)

        # Run pytest
        result = subprocess.run(
            [sys.executable, "-m", "pytest", test_file_path, "-v", "--tb=short", "--no-header"],
            capture_output=True, text=True, timeout=30,
            cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        )

        # Parse results
        stdout = result.stdout
        passed = stdout.count(" PASSED")
        failed = stdout.count(" FAILED")
        errors = stdout.count(" ERROR")

        return {
            "returncode": result.returncode,
            "stdout": stdout,
            "stderr": result.stderr,
            "passed": passed,
            "failed": failed,
            "errors": errors,
            "total": passed + failed + errors,
            "all_passed": result.returncode == 0,
        }
    except subprocess.TimeoutExpired:
        return {
            "returncode": -1, "stdout": "", "stderr": "Test execution timed out (30s)",
            "passed": 0, "failed": 0, "errors": 1, "total": 0, "all_passed": False,
        }
    except Exception as e:
        return {
            "returncode": -1, "stdout": "", "stderr": str(e),
            "passed": 0, "failed": 0, "errors": 1, "total": 0, "all_passed": False,
        }
    finally:
        # Restore backup
        if backup is not None:
            with open(file_path, "w") as f:
                f.write(backup)


def extract_python_code(response):
    """
    Extract Python code from a model response.
    Handles ```python fences, bare code, and mixed text+code.
    """
    response = response.strip()

    # Try to extract fenced code blocks
    if "```python" in response:
        blocks = response.split("```python")
        code_parts = []
        for block in blocks[1:]:
            end = block.find("```")
            if end >= 0:
                code_parts.append(block[:end].strip())
            else:
                code_parts.append(block.strip())
        return "\n\n".join(code_parts)

    if "```" in response:
        blocks = response.split("```")
        if len(blocks) >= 3:
            return blocks[1].strip()

    # If starts with def/import/class, treat as raw code
    for line in response.split("\n"):
        stripped = line.strip()
        if stripped.startswith(("def ", "import ", "from ", "class ")):
            return response

    return response
